//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRESORERIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIES_CENTRES_COUTS
    {
        public CATEGORIES_CENTRES_COUTS()
        {
            this.CENTRES_COUTS = new HashSet<CENTRES_COUTS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string LIBELLE { get; set; }
    
        public virtual ICollection<CENTRES_COUTS> CENTRES_COUTS { get; set; }
    }
}
