//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRESORERIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEPENSES
    {
        public int ID { get; set; }
        public Nullable<int> PROJET { get; set; }
        public Nullable<int> CENTRE_COUT { get; set; }
        public DateTime DATE { get; set; }
        public string TYPE_DOCUMENT { get; set; }
        public string NUMERO_DOCUMENT { get; set; }
        public string NUMERO_PIECE_COMPTABLE { get; set; }
        public string LIBELLE { get; set; }
        public decimal MONTANT_HT { get; set; }
        public decimal TVA { get; set; }
        public decimal FODEC { get; set; }
        public decimal TIMBRE { get; set; }
        public decimal RETENUE_SOURCE { get; set; }
        public Nullable<System.DateTime> DATE_PAIEMENT { get; set; }
        public Nullable<int> SOCIETE { get; set; }
        public Nullable<int> FOURNISSEUR { get; set; }
        public string MODALITE { get; set; }
    
        public virtual CENTRES_COUTS CENTRES_COUTS { get; set; }
        public virtual PROJETS PROJETS { get; set; }
        public virtual SOCIETES SOCIETES { get; set; }
        public virtual TIERS TIERS { get; set; }
    }
}
