//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRESORERIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURATIONS
    {
        public int ID { get; set; }
        public Nullable<int> PROJET { get; set; }
        public System.DateTime DATE_ECHEANCE_REGLEMENT { get; set; }
        public string TYPE_PIECE { get; set; }
        public string NUMERO_PIECE { get; set; }
        public string LIBELLE { get; set; }
        public Nullable<decimal> MONTANT_HT { get; set; }
        public Nullable<decimal> TVA { get; set; }
        public Nullable<decimal> TIMBRE { get; set; }
        public Nullable<decimal> RETENUE_SOURCE { get; set; }
        public Nullable<decimal> GARANTIE { get; set; }
        public Nullable<System.DateTime> DATE_REGLEMENT_REEL { get; set; }
        public Nullable<bool> ETAT_FACTURATION { get; set; }
        public Nullable<bool> ETAT_REGLEMENT { get; set; }
        public Nullable<int> SOCIETE { get; set; }
        public Nullable<System.DateTime> DATE_FACTURATION { get; set; }
        public Nullable<decimal> FODEC { get; set; }
        public Nullable<decimal> TTC { get; set; }
    
        public virtual PROJETS PROJETS { get; set; }
        public virtual SOCIETES SOCIETES { get; set; }
    }
}
