//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRESORERIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FACTURATIONS
    {
        public int ID { get; set; }
        public Nullable<int> PROJET { get; set; }
        public DateTime DATE_ECHEANCE_REGLEMENT { get; set; }
        public string TYPE_PIECE { get; set; }
        public string NUMERO_PIECE { get; set; }
        public string LIBELLE { get; set; }
        public decimal MONTANT_HT { get; set; }
        public decimal TVA { get; set; }
        public decimal TIMBRE { get; set; }
        public decimal RETENUE_SOURCE { get; set; }
        public decimal GARANTIE { get; set; }
        public Nullable<DateTime> DATE_REGLEMENT_REEL { get; set; }
        public bool ETAT_FACTURATION { get; set; }
        public bool ETAT_REGLEMENT { get; set; }
        public int SOCIETE { get; set; }
        public Nullable<DateTime> DATE_FACTURATION { get; set; }
        public decimal FODEC { get; set; }
        public decimal TTC { get; set; }
    
        public virtual PROJETS PROJETS { get; set; }
        public virtual SOCIETES SOCIETES { get; set; }
    }
}
