//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRESORERIE.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TresorerieEntities : DbContext
    {
        public TresorerieEntities()
            : base("name=TresorerieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ACHATS_PREVISIONNELS> ACHATS_PREVISIONNELS { get; set; }
        public DbSet<BUDGETS> BUDGETS { get; set; }
        public DbSet<CATEGORIES_CENTRES_COUTS> CATEGORIES_CENTRES_COUTS { get; set; }
        public DbSet<CENTRES_COUTS> CENTRES_COUTS { get; set; }
        public DbSet<DEPENSES> DEPENSES { get; set; }
        public DbSet<FACTURATIONS> FACTURATIONS { get; set; }
        public DbSet<FACTURATIONS_PREVISIONNELS> FACTURATIONS_PREVISIONNELS { get; set; }
        public DbSet<PROJETS> PROJETS { get; set; }
        public DbSet<SOCIETES> SOCIETES { get; set; }
        public DbSet<TIERS> TIERS { get; set; }
    }
}
