//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRESORERIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETS
    {
        public PROJETS()
        {
            this.BUDGETS = new HashSet<BUDGETS>();
            this.DEPENSES = new HashSet<DEPENSES>();
            this.FACTURATIONS = new HashSet<FACTURATIONS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NOM_PROJET { get; set; }
        public string TYPE { get; set; }
        public string CLIENT { get; set; }
        public string OWNER { get; set; }
        public DateTime DEBUT { get; set; }
        public DateTime FIN { get; set; }
        public decimal MONTANT_HT { get; set; }
        public decimal TVA { get; set; }
        public decimal GARANTIE { get; set; }
        public string TYPE_FACTURATION { get; set; }
        public string MODALITE_FACTURATION { get; set; }
        public Nullable<int> SOCIETE { get; set; }
    
        public virtual ICollection<BUDGETS> BUDGETS { get; set; }
        public virtual ICollection<DEPENSES> DEPENSES { get; set; }
        public virtual ICollection<FACTURATIONS> FACTURATIONS { get; set; }
        public virtual SOCIETES SOCIETES { get; set; }
    }
}
