//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRESORERIE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETS
    {
        public PROJETS()
        {
            this.ACHATS_PREVISIONNELS = new HashSet<ACHATS_PREVISIONNELS>();
            this.BUDGETS = new HashSet<BUDGETS>();
            this.DEPENSES = new HashSet<DEPENSES>();
            this.FACTURATIONS = new HashSet<FACTURATIONS>();
            this.FACTURATIONS_PREVISIONNELS = new HashSet<FACTURATIONS_PREVISIONNELS>();
        }
    
        public int ID { get; set; }
        public string CODE { get; set; }
        public string NOM_PROJET { get; set; }
        public string TYPE { get; set; }
        public Nullable<int> CLIENT { get; set; }
        public Nullable<int> OWNER { get; set; }
        public System.DateTime DEBUT { get; set; }
        public System.DateTime FIN { get; set; }
        public decimal MONTANT_HT { get; set; }
        public int TVA { get; set; }
        public decimal GARANTIE { get; set; }
        public string TYPE_FACTURATION { get; set; }
        public string MODALITE_FACTURATION { get; set; }
        public string REFERENCE { get; set; }
        public Nullable<int> SOCIETE { get; set; }
    
        public virtual ICollection<ACHATS_PREVISIONNELS> ACHATS_PREVISIONNELS { get; set; }
        public virtual ICollection<BUDGETS> BUDGETS { get; set; }
        public virtual ICollection<DEPENSES> DEPENSES { get; set; }
        public virtual ICollection<FACTURATIONS> FACTURATIONS { get; set; }
        public virtual ICollection<FACTURATIONS_PREVISIONNELS> FACTURATIONS_PREVISIONNELS { get; set; }
        public virtual SOCIETES SOCIETES { get; set; }
        public virtual TIERS TIERS { get; set; }
        public virtual TIERS TIERS1 { get; set; }
    }
}
